language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- yarn install
- yarn test
- yarn prepareDeploy
- git add -A && git commit -m "Updated version"
- echo -e "$NPM_USER\n$NPM_PASS\n$NPM_EMAIL" | npm adduser
- npm publish
