language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> .npmrc
- yarn install
- yarn test
- yarn prepareDeploy
- git add -A && git commit -m "Updated version"
- npm publish
